#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ALLOWLIST_FILE="${SCRIPT_DIR}/macos-settings-allowlist.txt"
WRITE_BASELINE_PATH=""

if [[ "${1:-}" == "--write-baseline" ]]; then
  if [[ $# -ne 2 ]]; then
    echo "Usage: $0 [--write-baseline /path/to/settings-baseline.sh]" >&2
    exit 1
  fi
  WRITE_BASELINE_PATH="$2"
fi

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "This script only runs on macOS." >&2
  exit 1
fi

if [[ ! -f "${ALLOWLIST_FILE}" ]]; then
  echo "Allowlist file not found: ${ALLOWLIST_FILE}" >&2
  exit 1
fi

normalize_bool() {
  case "${1}" in
    1|true|TRUE|yes|YES|on|ON) echo 1 ;;
    0|false|FALSE|no|NO|off|OFF) echo 0 ;;
    *)
      echo "unsupported bool value: ${1}" >&2
      return 1
      ;;
  esac
}

normalize_value() {
  local type="$1"
  local raw="$2"

  case "${type}" in
    bool)
      normalize_bool "${raw}"
      ;;
    int|float|string)
      # Keep values single-line and trimmed.
      echo "${raw}" | head -n 1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
      ;;
    *)
      echo "unsupported type: ${type}" >&2
      return 1
      ;;
  esac
}

entries=()
while read -r domain key type; do
  [[ -z "${domain}" || "${domain:0:1}" == "#" ]] && continue

  if ! raw_value="$(defaults read "${domain}" "${key}" 2>/dev/null)"; then
    echo "warning: missing key ${domain} ${key}" >&2
    continue
  fi

  value="$(normalize_value "${type}" "${raw_value}")"
  entries+=("${domain} ${key} ${type} ${value}")
done < "${ALLOWLIST_FILE}"

report_header="# Collected macOS settings from allowlist on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"

{
  echo "${report_header}"
  echo "# format: domain key type value"
  printf '%s\n' "${entries[@]}"
  echo
  echo "# Baseline snippet:"
  echo "macos_settings_entries() {"
  echo "  cat <<'SETTINGS'"
  printf '%s\n' "${entries[@]}"
  echo "SETTINGS"
  echo "}"
} 

if [[ -n "${WRITE_BASELINE_PATH}" ]]; then
  {
    echo "#!/bin/bash"
    echo "# Source of truth for allowlisted macOS settings."
    echo "# Generated by scripts/collect-macos-settings.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')."
    echo
    echo "macos_settings_entries() {"
    echo "  cat <<'SETTINGS'"
    printf '%s\n' "${entries[@]}"
    echo "SETTINGS"
    echo "}"
  } > "${WRITE_BASELINE_PATH}"
fi
